--- # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Install Packages
  hosts: all
  connection: ssh
  become: true
  become_method: sudo 
  tasks: 

  - name: Install web server on Amazon
    when: ansible_facts['distribution'] == "Amazon"
    package: 
      name: httpd 
      state: present 


  - name: Install web server On Ubuntu
    when: ansible_facts['distribution'] == "Ubuntu"
    package: 
      name: apache2 
      state: present 
