--- # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
- name: Add Package
  hosts: amazon
  connection: ssh
  user: ec2-user
  become: true
  become_method: sudo 
  tasks: 
  - name: Install telnet 
    package:
      name: telnet
      state: present